// app/components/downloads/download-table.vue
<template>
	<div class="download-table-padding">
		<table class="download-table">
			<thead>
				<tr class="download-heading">
					<th colspan="2" class="file-heading"><p>Name</p></th>
					<th><p>Date</p></th>
					<th colspan="2"><p>Downloads</p></th>
				</tr>
			</thead>
			<tbody>
				<download-version
					v-for="(items, version) in downloads"
					:key="version"
					:items
					:files
					:version
				/>
			</tbody>
		</table>
	</div>
</template>

<script>
import DownloadVersion from "./download-version.vue";

export default defineNuxtComponent({
	name: "download-table",
	components: {
		DownloadVersion,
	},
	props: {
		downloads: {
			type: Object,
			required: true,
		},
		files: {
			type: Array,
			required: false,
			default: () => [],
		},
	},
});
</script>

<style scoped lang="scss">
@use "~/assets/css/lib/variables" as *;

.download-table-padding {
	border-radius: $border-radius;
	padding: 0.7rem;
	overflow-x: auto;
	margin-bottom: 2rem;
}

.download-table {
	width: 100%;
}

.download-heading {
	background: $primary-button;
	border-radius: $border-radius;
	width: 100%;
	th {
		text-align: center;
		width: calc(40% / 3);
		p {
			font-size: 1.25rem;
			padding: 0.2rem;
			color: $secondary-text;
			margin-bottom: 0;
			vertical-align: middle;
		}
	}
}

// default middle text alignment looks really stupid
.file-heading {
	text-align: left !important;
	padding-left: 0.7rem;
	width: 50%;
}

// remove padding and table headers on mobile
@media (max-width: 760px) {
	.download-table-padding {
		margin: 0;
		padding: 0;
	}

	thead {
		display: none;
	}
}
</style>

// src/routes/[lang=lang]/downloads/downloadTable.svelte
<script lang="ts">
	import DownloadItem from "./downloadItem.svelte";
	export let downloads: App.DownloadList;
</script>

<div class="outline">
	<table class="download-table">
		<thead>
			<tr>
				<th colspan="2" class="large"><p>File</p></th>
				<th><p>Date</p></th>
				<th><p>Size</p></th>
				<th colspan="2"><p>Downloads</p></th>
			</tr>
		</thead>
		<tbody>
			{#each Object.entries(downloads) as [key, download]}
				<DownloadItem version={key} downloads={download} />
			{/each}
		</tbody>
	</table>
</div>

<style lang="scss">
	.outline {
		background: #131313 url(/images/background/bg_light_background.png) repeat;
		border-radius: $border-radius;
		padding: 0.7rem;
		overflow-x: auto;
		margin-bottom: 2rem;
	}
	.download-table {
		width: 100%;
		border-collapse: collapse;
	}
	thead > tr {
		background-color: #343a40;
		border-radius: $border-radius;
	}
	th > p {
		font-size: 20px;
		margin: 0;
	}
	th.large {
		text-align: left;
	}
	th > p,
	:global(td > p) {
		color: #ccc;
		padding: 0.2rem;
		margin-bottom: 0;
		vertical-align: middle;
	}

	@media (max-width: 760px) {
		.download-table thead {
			display: none;
		}
		.outline {
			margin: 0;
			padding: 0;
		}
	}
</style>
