// components/addons/addon-card.vue
<template>
	<article-card
		:href="'/addons/' + addon.slug"
		:image="'https://database.faithfulpack.net/images/addons/' + addon.slug + '/header'"
		:title="addon.name"
		:alt
	>
		<template #unlinked>
			<slot />
		</template>
		<template #linked>
			<div class="addon-flags" v-if="!minimal">
				<img
					v-if="addon.options.tags.includes('Java')"
					:src="java"
					alt="available for Java Edition"
					loading="lazy"
				/>
				<img
					v-if="addon.options.tags.includes('Bedrock')"
					:src="bedrock"
					alt="available for Bedrock Edition"
					loading="lazy"
				/>
				<img v-if="addon.options.optifine" :src="optifine" alt="requires optifine" loading="lazy" />
			</div>
			<div class="addon-res" v-if="!minimal">
				<p v-if="addon.options.tags.includes('32x')">32x</p>
				<p v-if="addon.options.tags.includes('64x')">64x</p>
			</div>
		</template>
	</article-card>
</template>

<script>
import ArticleCard from "../lib/article-card.vue";

export default {
	name: "addon-card",
	components: {
		ArticleCard,
	},
	props: {
		addon: {
			type: Object,
			required: true,
		},
		minimal: {
			type: Boolean,
			required: false,
			default: false,
		},
	},
	data() {
		return {
			optifine: "/image/addons/optifine.png",
			bedrock: "/image/addons/bedrock.png",
			java: "/image/addons/java.png",
		};
	},
	computed: {
		alt() {
			// take embed description if exists
			if (this.addon.embed_description) return this.addon.embed_description;
			// less than 150 characters (a lot of addons have really short descriptions)
			if (this.addon.description.length < 150) return this.addon.description;
			return this.addon.title;
		},
	},
};
</script>

<style scoped lang="scss">
@use "~/assets/css/lib/variables" as *;

.addon-flags {
	position: absolute;
	bottom: $card-padding;
	right: $card-padding;
	display: flex;
	flex-direction: column;

	& > img {
		height: 32px;
		width: 32px;
		border-radius: $border-radius-0x;
		margin-top: 5px;
	}
}

.addon-res {
	position: absolute;
	bottom: calc(#{$card-padding} + 14px);
	left: $card-padding;
	display: flex;
	flex-direction: row;

	& > p {
		margin-bottom: 0;
		margin-right: 1ch;
		color: rgba(255, 255, 255, 0.8);
	}
}
</style>

// src/components/addons/AddonCard.svelte
<script lang="ts">
    import Fa from "svelte-fa/src/fa.svelte";
	import { faStar, faXmark } from "@fortawesome/free-solid-svg-icons";
    import type { Addon, AddonTagArray, AddonTag } from "$interfaces/addons";
	import { favoriteStore } from "$stores/AddonStore";
    export let addon: Addon;

    $: [resolutions, editions] = addon.options.tags.reduce((acc: [AddonTagArray,AddonTagArray], cur: AddonTag[number]) => {
        let i: 0|1 = Number.isNaN(Number.parseInt(cur[0])) ? 1 : 0;
        acc[i].push(cur);
        return acc;
    }, [[],[]]);

    type FlagArray = (AddonTag[number] | "optifine")[];
    $: flags = (addon.options.optifine ? [...editions, "optifine"] : editions) as FlagArray;

    const src_flags = {
        "Java": "/images/icon/java.png",
        "Bedrock": "/images/icon/bedrock.png",
        "optifine": "/images/icon/optifine.png",
    } as Record<FlagArray[number], string>;

    const alt_flags = {
        "Java": "available for Java Edition",
        "Bedrock": "available for Bedrock Edition",
        "optifine": "requires optifine",
    } as Record<FlagArray[number], string>;;
</script>
<div class="hovering-effect">
	<a href={'/add-ons/' + addon.slug } class="card img-card">
        <span class={"addon-favorite " + ($favoriteStore.favorites.includes(String(addon.id)) ? "remove" : "add")} on:click|preventDefault={() => favoriteStore.toggle(String(addon.id))} on:keypress={() => {}}>
            <Fa icon={$favoriteStore.favorites.includes(String(addon.id)) ? faXmark : faStar } size="1x" translateY={-0.2} />
        </span>
        <img
			src={`https://database.faithfulpack.net/images/addons/${ addon.slug }/header?w=570`}
			loading="lazy"
            alt={addon.name}
		/>
		<div class="img-card-shadow" />
        <div class="img-bottom">
            <div class="addon-tags">
                {#each resolutions as resolution }
                    <p>{ resolution }</p>
                {/each}
            </div>
            <h3>{addon.name}</h3>
        </div>
        <div class="addon-flags" style="margin-bottom: 5px;">
            {#each flags as flag}
                <img
                    src={src_flags[flag]}
                    alt={alt_flags[flag]}
                    loading="lazy"
                />
            {/each}
        </div>
	</a>
</div>

<style lang="scss">
    .hovering-effect {
        transition: transform .2s;

        &:hover {
            transform: scale(1.025);
        }
    }
    .img-card-shadow {
        position: absolute;
        top: 0;
        width: 100%;
        height: 100%;
        -webkit-box-shadow: inset 5px 5px 50px 25px rgba(0,0,0,0.5);
        box-shadow: inset 5px 5px 50px 25px rgba(0,0,0,0.5);
    }
    .img-card > .img-bottom {
        right: 37px;

        h3 {
            font-size: 1rem;
            color: rgba(255, 255, 255, 1);
        }
    }
    .addon-flags {
        position: absolute;
        bottom: 5px;
        right: 5px;
        display: flex;
        flex-direction: column;

        & > img {
            height: 32px;
            width: 32px;
            border-radius: $border-radius;
            margin-top  : 5px;

            & + img {
                margin-right: 5px;
            }
        }
    }
    .addon-tags {
        display: flex;
        flex-direction: row;
        margin-bottom: calc(-8px - 3px);
        margin-left: 8px;

        & > p {
            margin: 0 5px 5px 0;
            color: rgba(255, 255, 255, 1);
        }
    }
    .addon-favorite {
        position: absolute;
        top: 0;
        left: 0;
        z-index: 3;
        padding: 8px;

        &.add {
            color: rgba(0,0,0,0.5);
        }
        &.remove {
            color: red;
        }
    }
</style>
