// src/routes/downloads/downloadTable.svelte
<script lang="ts">
	import DownloadItem from "./downloadItem.svelte";
	export let downloads: DownloadList;
</script>

<div class="outline">
	<table class="download-table">
		<thead>
			<tr>
				<th colspan="2" class="large"><p>Version</p></th>
				<th colspan="2"><p>Downloads</p></th>
				<th><p>Size</p></th>
				<th><p>Date</p></th>
			</tr>
		</thead>
		<tbody>
			{#each Object.entries(downloads) as [key, download]}
				<DownloadItem version={key} downloads={download} />
			{/each}
		</tbody>
	</table>
</div>

<style lang="scss">
	.outline {
		background: #131313 url(/images/background/bg_light_background.png) repeat;
		border-radius: $border-radius;
		padding: 0.7rem;
		overflow-x: auto;
		margin-bottom: 2rem;
	}
	.download-table {
		width: 100%;
		border-collapse: collapse;
	}
	thead > tr {
		background-color: #343a40;
		border-radius: $border-radius;
	}
	th > p {
		font-size: 20px;
		margin: 0;
	}
	th.large {
		text-align: left;
	}
	th > p,
	:global(td > p) {
		color: #ccc;
		padding: 0.2rem;
		margin-bottom: 0;
		vertical-align: middle;
	}

	@media (max-width: 760px) {
		.download-table thead {
			display: none;
		}
		.outline {
			margin: 0;
			padding: 0;
		}
	}
</style>

// app/components/downloads/archive/download-table.vue
<template>
	<div class="download-table-padding accent-textured">
		<table class="download-table">
			<thead class="download-heading">
				<tr>
					<!-- these must be in divs, I have no idea why -->
					<th />
					<th class="text-left"><h4>Name</h4></th>
					<th><h4>Published</h4></th>
					<th><h4>Downloads</h4></th>
				</tr>
			</thead>
			<tbody>
				<download-version
					v-for="(items, version) in downloads"
					:key="version"
					:items
					:files
					:version
				/>
			</tbody>
		</table>
	</div>
</template>

<script>
import DownloadVersion from "./download-version.vue";

export default defineNuxtComponent({
	name: "download-table",
	components: {
		DownloadVersion,
	},
	props: {
		downloads: {
			type: Object,
			required: true,
		},
		files: {
			type: Array,
			required: false,
			default: () => [],
		},
	},
});
</script>

<style scoped lang="scss">
@use "~/assets/css/variables" as *;

.download-table-padding {
	border-radius: $border-radius;
	// half of the horizontal padding goes here and half in the highlight
	padding: $padding-card calc($padding-card / 2);
	overflow-x: auto;
	box-shadow: $shadow-card;
}

// for mobile
.download-table {
	width: 100%;
}

.download-heading h4 {
	color: $text-card-title;
	font-size: 1.25rem;
	margin-bottom: 0;
	padding-bottom: $padding-card;
}

// remove table headers on mobile
@media screen and (max-width: $breakpoint-sm) {
	thead {
		display: none;
	}
}
</style>
