// src/routes/[lang=lang]/[slug]/[slug]/+page.svelte
<script lang="ts">
	import { marked } from 'marked';
    import type { PageData } from './$types';
	import DownloadButton from '$components/common/downloadButton.svelte';
	import DiscordBanner from '$components/common/discordBanner.svelte';
	import ChangeLog from "./changeLog.svelte"

    export let data: PageData;
</script>


{#if data.discontinued}
<div class="container"><h2 class="red banner">This project has been discontinued.</h2></div>
{/if}

<div class="container">
	{#if data.title}
		<h1 class="text-center title">{ data.title }</h1>
	{:else}
		<h1 class="text-center title">{ data.title }</h1>
	{/if}
	<div class="post-details">
		<div class="post-details-left">
			<!--{#if data.authors }
				<h3 class="display text-center">
				By&nbsp;
				{#each data.authors as author, i}
					{#if typeof(author) === 'string' }
						{#if i != data.authors.length }
							{ author },
						{:else}
							{ author }
						{/if}
					{:else}
						{#if i != data.authors.length }
							<a href="{ author.first }">{ author.first }</a>,
						{:else}
							<a href="{ author.first }">{ author.first }</a>
						{/if}
					{/if}
				{/each}
			</h3>
		{/if}-->
		{#if data.downloads}
			{#if Object.keys(data.downloads).length > 1}
				<h2 class="text-center">Downloads</h2>
			{:else}
				<h2 class="text-center">Download</h2>
			{/if}
			{#each Object.entries(data.downloads) as [title, items] }
				<h3 class="my-3 text-center">{title}</h3>
				{#each items as item}
					<DownloadButton href={item.url} text={item.name} />
				{/each}
			{/each}
		{/if}
		</div>
		<div class="post-details-right">
			{#if data.headerImg}
				<img id="post-header-img" class="fancy-card-1x card" src={data.headerImg} alt={data.title} />
			{/if}

			<div class="card card-body">
				<p id="text" class="m-0">
					{@html marked.parseInline(data.description, {
						breaks: true,
					})}
				</p>
			</div>
		</div>
	</div>

	<DiscordBanner text="discussion" />

	{#if data.changelog}
		<h2 class="subtitle semibold my-5 text-center">Changelog</h2>
		<div class="card card-body my-5 changelog">
			<ChangeLog changelog={data.changelog} />
		</div>
	{/if}
</div>

<style lang="scss">
	.post-details {
		display: flex;
        flex-wrap: wrap;

		&-left {
			flex: 0 0 25%;
		}

		&-right {
			flex: 0 0 75%;
            padding-left: 20px;

			.card {
				margin-top: 20px;
			}
		}
	}

	#text {
		text-align: justify;
		line-height: 1.5;
	}

	#post-header-img {
		width: 100%;
	}

	@media(max-width: $width-S) {
        .post-details {
            flex-direction: column-reverse;

            &-right {
                padding-left: 0;
            }
        }
    }
</style>

// pages/[...slug].vue
<template>
	<p v-if="post.discontinued" class="red banner h2">This project has been discontinued.</p>
	<h1 v-if="post.title" class="title my-5 text-center">{{ post.title }}</h1>
	<template v-if="post.header_img">
		<img :src="post.header_img" class="header-img" style="width: 100%" />
		<br />
	</template>

	<hr />

	<div
		v-if="post.description"
		class="card card-body card-text"
		v-html="compiledMarkdown(post.description)"
	/>
	<post-downloads v-if="Object.keys(post.downloads).length" :downloads="post.downloads" />
	<template v-if="Object.keys(post.changelog).length">
		<br />
		<h2 class="subtitle my-5 text-center">Changelog</h2>
		<div class="card card-body">
			<post-changelog :item="post.changelog" />
		</div>
	</template>
	<br />
	<discord-button />
</template>

<script>
import DiscordButton from "~/components/lib/discord-button.vue";
import PostChangelog from "~/components/posts/post-changelog.vue";
import PostDownloads from "~/components/posts/post-downloads.vue";
import DOMPurify from "isomorphic-dompurify";
import { marked } from "marked";

export default defineNuxtComponent({
	components: {
		DiscordButton,
		PostDownloads,
		PostChangelog,
	},
	async asyncData() {
		const route = useRoute();
		const post = await $fetch(
			`https://api.faithfulpack.net/v2/posts/${encodeURIComponent(encodeURIComponent(route.path))}`,
		);
		return { post };
	},
	methods: {
		compiledMarkdown(text) {
			return DOMPurify.sanitize(marked.parse(text));
		},
	},
});
</script>

<style scoped lang="scss">
.hero {
	display: block;
	background-image: v-bind(banner);
	background-size: cover;
	background-position: center;
	padding: 0 2rem 1px;
	text-align: center;
}

.wordmark {
	padding: 5vw;
	filter: drop-shadow(0 0 10px #000);
	width: 800px;
}
</style>
