// src/routes/[lang=lang]/about/+page.svelte
<script>
    import Fa from "svelte-fa/src/fa.svelte";
	import {
		faAngleRight
	} from "@fortawesome/free-solid-svg-icons";
</script>

<div class="section green">
    <div>
        <h1>UPSCALING THE LOOK OF MINECRAFT</h1>
        <p>Faithful aims to re-create Minecraft's original textures at higher resolutions, while staying true to their original look and feel.</p>
        <a class="button" href="https://docs.faithfulpack.net/pages/textures/contributor-handbook" target="_blank" rel="noreferrer">HOW TO CONTRIBUTE<Fa icon={faAngleRight} /></a>
    </div>
    <img src="/images/about/1.png" alt="placeholder">
</div>
<div class="section">
    <img src="/images/about/2.png" alt="placeholder">
    <div>
        <h1>FREE AND OPEN-SOURCE</h1>
        <p>
            All our textures, as well as the code of all our related projects, are available on GitHub.
            <br>
            Anybody's welcome to contribute, take a look!
        </p>
        <a class="button button-theme" href="https://github.com/Faithful-Resource-Pack" target="_blank" rel="noreferrer">VISIT OUR GITHUB<Fa icon={faAngleRight} /></a>
    </div>
</div>
<div class="section blue">
    <div>
        <h1>CROSS-PLATFORM</h1>
        <p>Faithful is available for many Java Edition versions as well as Bedrock Edition. This means it can be used on all devices that support manual installation of resource packs.</p>
        <a class="button" href="/installation">HOW TO INSTALL<Fa icon={faAngleRight} /></a>
    </div>
    <img src="/images/about/3.png" alt="placeholder">
</div>
<div class="section">
    <img src="/images/about/2.png" alt="placeholder">
    <div>
        <h1>MADE BY THE COMMUNITY</h1>
        <p>The project is made possible entirely by talented volunteer artists and developers working in their free time. Faithful is all about the fans – Come talk to us and get involved!</p>
        <a class="button button-theme" href="https://discord.gg/sN9YRQbBv7" target="_blank" rel="noreferrer">JOIN OUR DISCORD<Fa icon={faAngleRight} /></a>
    </div>
</div>
<div class="section pink">
    <div>
        <h1>A HISTORY OF SOMETHING</h1>
        <p>[placeholder title] We've got an over-a-decade-long history of making quality textures for Minecraft. Being one of the first ever texture packs to be developed, Faithful has secured its place among the most well-known Minecraft projects.</p>
        <a class="button" href="/history">READ MORE<Fa icon={faAngleRight} /></a>
    </div>
    <img src="/images/about/4.png" alt="placeholder">
</div>
<div class="faq">
    <h1>ANY MORE QUESTIONS?</h1>
    <a class="button button-theme" href="/faq">VIEW FAQ<Fa icon={faAngleRight} /></a>
</div>

<style lang="scss">
    .section {
        padding: 30px 20%;
        display: flex;
        align-items: center;
        gap: 40px;

        p {
            margin-bottom: 34px;
        }
    }

    .faq {
        display: flex;
        flex-direction: column;
        align-items: center;
        padding-top: 80px;
        // Only padding 30px and not 80px because the body already has a padding of 50px at the bottom
        padding-bottom: 30px;

        h1 {
            margin-top: 0;
            text-align: center;
        }
    }

    .button {
            background: #fff;
            font-size: 1.1rem;
            font-weight: 600;
            padding: 12px 22px;
            border-radius: $border-radius;
        }

    .green {
        background: #76c944 url("/images/background/bg_light_foreground.png") repeat;
        background-blend-mode: multiply;

        h1, p {
            color: #fff;
        }

        .button {
            color: #76c944;
        }
    }

    .blue {
        background: #3498db url("/images/background/bg_light_foreground.png") repeat;
	    background-blend-mode: multiply;
        height: 460px;

        div {
            z-index: 1;
            width: 40%;
        }

        h1, p {
            color: #fff;
        }

        img {
            height: 400px;
            position: absolute;
            right: 140px;
        }

        .button {
            color: #3498db;
        }
    }

    .pink {
        background: #ac1e63 url("/images/background/bg_light_foreground.png") repeat;
        background-blend-mode: multiply;

        h1, p {
            color: #fff;
        }

        .button {
            color: #ac1e63;
        }
    }

    @media (max-width: 1820px) {
	    .blue img {
            right: 30px;
        }
    }

    @media (max-width: $width-L) {
	    .section {
	    	padding: 30px 30px;
	    }

        .blue img {
            width: 100%;
            height: auto;
            left: 0;
            right: 0;
            padding: 0 30px;
        }
    }

    @media (max-width: $width-M) {
	    .section {
	    	flex-wrap: wrap;
            justify-content: center;

            div {
                display: flex;
                flex-direction: column;
                align-items: center;
                text-align: center;
            }
	    }

        .blue {
            height: auto;

            div {
                width: 100%;
            }

            img {
                position: static;
                width: 100%;
                height: auto;
            }
        }
    }
</style>

// pages/about.vue
<script setup>
definePageMeta({
	layout: "no-container",
});
</script>

<template>
	<div class="green-background">
		<div class="container about-container">
			<div class="about-text">
				<h1 class="about-title">Upscaling the Look of Minecraft</h1>
				<p>
					Faithful recreates Minecraft's original textures in higher resolutions while staying true
					to their original look and feel.
					<br /><br />
					With multiple resolutions and styles, everyone can find a pack they like!
				</p>
				<a
					class="about-button"
					href="https://discord.gg/sN9YRQbBv7"
					target="_blank"
					rel="noreferrer"
				>
					Join our Discord <v-icon icon="mdi-chevron-right" />
				</a>
			</div>
			<img class="about-image" src="/image/about/faithful.gif" alt="gif of creeper textures" />
		</div>
	</div>
	<div class="container about-container">
		<img class="about-image" src="/image/about/foss.png" alt="github screenshot" />
		<div class="about-text">
			<h1 class="about-title">Free and Open-Source</h1>
			<p>
				The project is made possible entirely by talented volunteer artists and developers working
				in their free time.
				<br /><br />
				All of our textures, as well as the code of all our related projects, are available on
				GitHub. Take a look and see how the magic happens!
			</p>
			<a
				class="about-button"
				href="https://github.com/Faithful-Resource-Pack"
				target="_blank"
				rel="noreferrer"
			>
				Visit our GitHub <v-icon icon="mdi-chevron-right" />
			</a>
		</div>
	</div>
	<div class="blue-background">
		<div class="container about-container">
			<div class="about-text">
				<h1 class="about-title">Cross-platform</h1>
				<p>
					Faithful is available for both the most popular Java Edition versions as well as Bedrock
					Edition.
					<br /><br />
					This means it can be used on all devices that support manual installation of resource
					packs, from phones to even certain consoles.
				</p>
				<a class="about-button" href="/downloads">
					View Downloads <v-icon icon="mdi-chevron-right" />
				</a>
			</div>
			<img class="about-image" src="/image/about/platforms.png" alt="supported platforms" />
		</div>
	</div>
	<div class="container about-container">
		<img class="about-image" src="/image/about/community.png" alt="the faithful community" />
		<div class="about-text">
			<h1 class="about-title">Made by the Community</h1>
			<p>
				All Faithful textures are voted on by the public before being added, and anyone can submit a
				texture to any project with no strings attached.
				<br /><br />
				Simply read our contribution handbook and follow the steps—it's that easy to make your mark
				on Faithful forever!
			</p>
			<a
				class="about-button"
				href="https://docs.faithfulpack.net/pages/manuals/contributor-handbook"
				target="_blank"
				rel="noreferrer"
				>How to Contribute <v-icon icon="mdi-chevron-right" />
			</a>
		</div>
	</div>
	<div class="pink-background">
		<div class="container about-container">
			<div class="about-text">
				<h1 class="about-title">A History of Expertise</h1>
				<p>
					We've got over a decade of experience making quality textures for Minecraft, with a rich
					history spanning from the first releases up to today.
					<br /><br />
					As one of the first ever texture packs to be developed, having started all the way back in
					2010, Faithful has secured its place among the most well-known Minecraft projects.
				</p>
				<a class="about-button" href="/stats">
					See our Stats <v-icon icon="mdi-chevron-right" />
				</a>
			</div>
			<img class="about-image" src="/image/about/history.png" alt="our history" />
		</div>
	</div>
	<div class="container faq-section">
		<h1 class="mb-4">Any More Questions?</h1>
		<a class="about-button" href="/faq">
			View our FAQ <v-icon icon="mdi-chevron-right" class="ma-0" />
		</a>
	</div>
</template>

<style scoped lang="scss">
@use "~/assets/css/lib/variables" as *;

.about-image {
	max-height: 384px;
	filter: drop-shadow(0 10px 10px #00000077);
}

// override container class for flex content
.about-container {
	width: 100%;
	display: flex;
	align-items: center;
	justify-content: center;
	gap: 40px;

	h1 {
		text-transform: uppercase;
	}

	p {
		// add a bit of padding between the button and text
		padding-bottom: 1.5rem;
	}
}

.faq-section {
	display: flex;
	flex-direction: column;
	align-items: center;
	padding-top: 80px;
	padding-bottom: 80px;

	h1 {
		margin-top: 0;
		text-align: center;
		text-transform: uppercase;
	}
}

.about-button {
	padding: 12px 22px;
	// prevent weird button wrapping issues
	white-space: nowrap;
	text-transform: uppercase;
	line-height: 1;
	transition: all 0.2s ease;
	&:hover {
		opacity: 0.66;
	}
}

.green-background {
	// both light/dark mode use white text
	p {
		color: #fff;
	}

	.about-button {
		background: white !important;
		color: $about-green-dark !important;
	}
}

.blue-background {
	p {
		color: #fff;
	}

	.about-button {
		background: white !important;
		color: $about-blue-dark !important;
	}
}

.pink-background {
	p {
		color: #fff;
	}

	.about-button {
		background: white !important;
		color: $about-pink-dark !important;
	}
}

@media (max-width: 1080px) {
	// center content and display vertically on mobile
	.about-container {
		display: flex;
		flex-direction: column;
		align-items: center;
		text-align: center;
		max-width: 95%;
	}
}

@media (max-width: 1200px) {
	// override container class to fix margins
	.container {
		max-width: 95% !important;
	}
}
</style>
